server:
  port: 1988
spring:
  application:
    name: customer-service
  datasource:
    username: 'root'
    password:
    url: jdbc:mysql://localhost:3306/db_cutomers?serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql : true
    hibernate :
      ddl-auto : update
    show-sql : true
eureka:
  client:
    service-url:
      defaultZone : http//localhost:8761/eureka
    fetch-registry: true
    register-with-eureka:  true

